### ISSUE TITLE
Incompatibility with Farsight

### ISSUE THREAD

**Issue by Freshah** [FionaTheMortal/Better-Biome-Blend#50]
Farsight also adds a slider to the "Video Settings" menu, and it seems to overwrite BBB's slider on 1.18 Forge.

It successfully hid the vanilla slider too?

**Comment by FionaTheMortal** [comment]
BBB hides the slider because it now always uses the max setting. This is because small and large blend radii would require different algorithms for generation and storage to be efficient.

Does Farsight rely on the Biome Blend option for it's own code? I would reenable to slider then for compatibility but it seems silly to have a slider in the options that doesn't do anything.

**Comment by Freshah** [comment]
From what you've just said, this isn't an issue at all then.   my apologies!
